elasticsearch:
  global:
    kibanaEnabled: true





fluent-bit:
  logLevel: info
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush {{ .Values.flush }}
          Log_Level debug
          Parsers_File /fluent-bit/etc/parsers.conf
          Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.metricsPort }}
          Health_Check On
          Trace_Error On

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*commercial*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 100MB
          Skip_Long_Lines On

      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On

    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          Buffer_Size False
          K8S-Logging.Parser On
      
    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          Name es
          Match kube.*
          Index fluent-bit
          Type  _doc
          Host elasticsearch
          Port 9200
          tls Off
          tls.verify Off
          Logstash_Format On
          Logstash_Prefix storelogs
          Retry_Limit False
          Suppress_Type_Name On

      [OUTPUT]
          Name es
          Match host.*
          Index fluent-bit
          Type  _doc
          Host elasticsearch
          Port 9200
          tls Off
          tls.verify Off
          Logstash_Format On
          Logstash_Prefix node
          Retry_Limit False
          Suppress_Type_Name On
    # customParsers: |
    #   [PARSER]
    #       Name json_parser
    #       Format json
    #       Time_Key time
    #       Time_Format %Y-%m-%dT%H:%M:%S.%NZ

    #   [PARSER]
    #       Name regex_parser
    #       Format regex
    #       Regex /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
    #       Time_Format %Y-%m-%dT%H:%M:%S.%N%:z