deployment:
  name: commercial-store
  labels:
    app: commercial-store
  containers: commercial-store
  selector:
    app: commercial-store

service:
  name: commercial-store
  labels:
    app: commercial-store
  selector:
    app: commercial-store
  type: ClusterIP
  ports:
    port: 80
    targetPort: 5000

postgresql:
  architecture: standalone
  auth:
    existingSecret: postgresql-secret
    secretKeys:
      adminPasswordKey: postgres-admin-password
      userPasswordKey: postgres-user-password
      replicationPasswordKey: postgres-repl-password

  persistence:
    enabled: true
  primary:
    initdb:
      scriptsConfigMap: initdb-script