apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: commercial-store
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: "lior-levi-proj=644435390668.dkr.ecr.us-east-1.amazonaws.com/lior-levi-proj:*" # :semver:~1.0 "semver", update to highest version
    argocd-image-updater.argoproj.io/write-back-method: git # commit changes to Git repo
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/lior-levi-proj.update-strategy: latest
    argocd-image-updater.argoproj.io/lior-levi-proj.force-update: "true"
    # argocd-image-updater.argoproj.io/lior-levi-proj.helm.image-name: deployment.image.name
    # argocd-image-updater.argoproj.io/lior-levi-proj.helm.image-tag: deployment.image.tag
    argocd-image-updater.argoproj.io/lior-levi-proj.helm.image-spec: image.tag
    # argocd-image-updater.argoproj.io/lior-levi-proj.helm.image-spec: "deployment.image"

spec:
  project: default
  source:
    repoURL: git@github.com:lior-eng/gitops.git
    path: apps/commercial-store
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true