apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:lior-eng/gitops.git
    targetRevision: HEAD
    path: apps/kps
    helm:
      valueFiles:
        - "$mycharts/apps/kps-values.yaml"
      # values: |
      #   installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true