apiVersion: v1
kind: ConfigMap
metadata: 
  name: commercial-store-cm
data:
  DB_HOST: {{ .Values.configmap.data.db_host | quote }}
  POSTGRES_PORT: {{ .Values.configmap.data.postgres_port | quote }}
  POSTGRES_DB: {{ .Values.configmap.data.postgres_db | quote }}
  POSTGRES_USER: {{ .Values.configmap.data.postgres_user | quote }}
  LOG_LEVEL: {{ .Values.configmap.data.log_level | quote }}