apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    {{- toYaml .Values.deployment.labels | nindent 4 }}
spec:
  replicas: 2
  selector: 
    matchLabels:
      {{- toYaml .Values.deployment.selector | nindent 8 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.deployment.labels | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.deployment.containers }}
        image: {{ .Values.deployment.image }}
        # command: ["sleep", "3600"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: commercial-store-cm
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                # key: postgres-user-password
                key: postgres-password
        ports:
        - containerPort: 5000