apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- toYaml .Values.service.labels | nindent 4 }}
spec:
  selector:
    {{- toYaml .Values.service.selector | nindent 4 }}
  ports:
  - port: {{ .Values.service.ports.port }}
    protocol: TCP
    targetPort: {{ .Values.service.ports.targetPort }}
  type: {{ .Values.service.type }}