helm:
  parameters:
  - name: image.repository
    value: 644435390668.dkr.ecr.us-east-1.amazonaws.com/lior-levi-proj
    forcestring: false
  - name: image.tag
    value: v1.0.52
    forcestring: true
  - name: image.name
    value: 644435390668.dkr.ecr.us-east-1.amazonaws.com/lior-levi-proj
    forcestring: true
