helm:
  parameters:
  - name: image.name
    value: 644435390668.dkr.ecr.us-east-1.amazonaws.com/lior-levi-proj
    forcestring: true
  - name: deployment.image.tag
    value: v1.0.39
    forcestring: true
